version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
          time: '13:00'
      open-pull-requests-limit: 10
      groups:
          babel-updates:
              patterns:
                  - '@babel/*'
    # atomizer
    - package-ecosystem: npm
      directory: '/packages/atomizer'
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
    # grunt-atomizer
    - package-ecosystem: npm
      directory: '/packages/grunt-atomizer'
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
