version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: daily
          time: '13:00'
      open-pull-requests-limit: 10
    # atomizer
    - package-ecosystem: npm
      directory: '/packages/atomizer'
      schedule:
          interval: daily
      open-pull-requests-limit: 10
    # grunt-atomizer
    - package-ecosystem: npm
      directory: '/packages/grunt-atomizer'
      schedule:
          interval: daily
      open-pull-requests-limit: 10
