language: node_js
matrix:
  allow_failures:
    - node_js: "11"
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
after_success:
  - "npm run cover"
  - "cat artifacts/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
