name: CI

on:
    pull_request:
        types: [opened, synchronize]
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@latest
            - name: Setup node
              uses: actions/setup-node@latest
              with:
                  node-version: 20
            - name: Install Dependencies
              run: npm install
            - name: Lint code
              run: npm run lint
            - name: Format code
              run: npm run format
            - name: Build code
              run: npm run build
            - name: Test code
              run: npm run test
    publish:
        runs-on: ubuntu-latest
        needs: [test]
        if: "${{ github.repository_owner == 'acss-io' && github.event_name == 'push' }}"
        steps:
            - name: Checkout code
              uses: actions/checkout@latest
            - name: Setup node
              uses: actions/setup-node@latest
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Build code
              run: npm run build
            - name: Publish to npm
              id: changesets
              uses: changesets/action@v1
              with:
                  version: npm run version
                  publish: npm run publish
                  commit: '[ci] publish'
                  title: '[ci] publish'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Publish VSCode extension
              continue-on-error: true
              run: |
                  npm run package -w atomic-css-snippets
                  npm run deploy -w atomic-css-snippets
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
    site:
        runs-on: ubuntu-latest
        if: "${{ github.repository_owner == 'acss-io' && github.event_name == 'push' }}"
        steps:
            - name: Checkout code
              uses: actions/checkout@latest
            - name: Setup node
              uses: actions/setup-node@latest
              with:
                  node-version: 20
            - name: Install Dependencies
              run: npm install
            - name: Build code
              run: npm run build
            # Use GitHub Actions' cache to shorten build times and decrease load on servers
            - name: Setup vendor cache
              uses: actions/cache@v2
              with:
                  path: vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-
            - name: Deploy to GitHub pages
              uses: helaili/jekyll-action@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  jekyll_src: 'docs'
                  target_branch: 'gh-pages'
